Add a navbar
terrifricker/chingu-practice-toucans-03 pull request #19
Opened 2023-01-05 22:56 UTC by terrifricker

**Closes Issue#14 - Add a navbar**

Add a simple nav bar with just a title "Chingu Voyage 24" and the name of our team "Team Toucan 03"

Using the google color picker, I chose a pretty yellow for the background of the nav, then chose a light and dark color from the same hue as a background color for main and for the border colors.  [My pretty yellow](https://g.co/kgs/Vwh4ZX)

Add the yellows as css variables in :root

2023-01-05 23:03 UTC, Medic1111 submitted a review, later dismissed
Awesome job opening PR to dev!

2023-01-05 23:03 UTC, alekzandriia requested changes
I like it, but maybe instead of using absolute sizing units (px,pt), we could consistently use relative units (em, rem,etc.) so that it's responsive & looks pretty on every device? :)

2023-01-05 23:04 UTC, Medic1111 commented
> I like it, but maybe instead of using absolute sizing units (px,pt), we could consistently use relative units (em, rem,etc.) so that it's responsive & looks pretty on every device? :)

WOW, great job TEAM!!!!

2023-01-05 23:56 UTC, terrifricker commented on index.html
> -            <nav></nav>
I don't actually know how to accept this change right here in the GitHub review window.

2023-01-05 23:58 UTC, terrifricker commented on index.html
> -            <nav></nav>
Oh, this is actually the change that **I** made for the pull request.

2023-01-06 00:22 UTC, terrifricker commented
Changes requested made.

Changed px units to responsive rem units for padding and gap.

2023-01-06 00:24 UTC, alekzandriia approved these changes

2023-01-06 00:24 UTC, terrifricker commented
@alekzandriia  - I am now realizing that I didn't change the pt units.  How do we feel about leaving points as units for borders?

2023-01-06 00:26 UTC, alekzandriia commented
> @alekzandriia  - I am now realizing that I didn't change the pt units.  How do we feel about leaving points as units for borders?

I noticed that. I think it's fine for small borders. In the official project, prior to pushing to main, we'd probably wanna test it out on multiple devices to be 💯 sure, but I think it's good. 😁

2023-01-06 00:27 UTC, Medic1111 approved these changes

2023-01-06 17:12 UTC, QuangLyHo approved these changes

2023-01-06 17:15 UTC, merged